document.addEventListener('DOMContentLoaded', function() {
    const translations = {
        "it": {
            "title": "500 Crypto - La Fiat 500 d'epoca",
            "header_title": "500 Crypto",
            "header_subtitle": "La criptovaluta che celebra il mito della Fiat 500 d'epoca",
            "about_title": "Chi Siamo",
            "about_text": "Benvenuti nel mondo di 500 Crypto, la criptovaluta che celebra il mito della Fiat 500 d'epoca. Unisciti a noi per rivivere la magia di questa iconica automobile.",
            "about_mission_label": "Missione:",
            "about_mission_text": "Siamo appassionati dell'iconica Fiat 500 d'epoca e crediamo che la sua storia e il suo design unico meritino una celebrazione nel mondo delle criptovalute. Il nostro obiettivo è creare una community di appassionati, unendo il fascino del passato con le innovazioni del futuro.",
            "what_is_title": "Cos'è 500 Crypto?",
            "what_is_text_1": "500 Crypto è una criptovaluta basata sulla blockchain di Solana. È stata creata per celebrare la Fiat 500 d'epoca, una delle auto più iconiche e amate di tutti i tempi. Il token mira a creare una community di appassionati di auto d'epoca e di criptovalute.",
            "what_is_keypoints_label": "Punti Chiave:",
            "what_is_keypoint_1": "<strong>Community:</strong> Unisce appassionati di auto d'epoca e criptovalute.",
            "what_is_keypoint_2": "<strong>Decentralizzata:</strong> Opera sulla blockchain di Solana.",
            "what_is_keypoint_3": "<strong>Obiettivo:</strong> Celebra la Fiat 500 d'epoca.",
            "roadmap_title": "Roadmap",
            "roadmap_phase_1_label": "Fase 1:",
            "roadmap_phase_1_text": "Lancio del token e creazione della community. (Completa)",
            "roadmap_phase_2_label": "Fase 2:",
            "roadmap_phase_2_text": "Sviluppo di partnership con eventi dedicati ad auto d'epoca. (In corso)",
            "roadmap_phase_3_label": "Fase 3:",
            "roadmap_phase_3_text": "Creazione di una piattaforma per lo scambio di asset legati alla Fiat 500 (prossimamente)",
            "gallery_title": "Galleria",
            "chart_title": "Grafico della Criptovaluta su Solana",
            "stats_title": "Statistiche della Criptovaluta",
            "stats_text": "Per visualizzare le statistiche della criptovaluta, visita la pagina ufficiale su ",
            "stats_link": "pump.fun",
            "contact_title": "Contattaci",
            "contact_name_label": "Nome:",
            "contact_email_label": "Email:",
            "contact_message_label": "Messaggio:",
            "contact_send_button": "Invia",
            "footer_rights": "Tutti i diritti riservati.",
            "whitepaper_title": "White Paper",
            "whitepaper_intro_title": "Introduzione",
            "whitepaper_intro_text": "500 Crypto è una criptovaluta basata sulla blockchain di Solana, creata per celebrare l'iconica Fiat 500 d'epoca. Questo token unisce il fascino del passato con le innovazioni del futuro.",
            "whitepaper_vision_title": "Visione e Missione",
            "whitepaper_vision_text": "La nostra visione è creare una criptovaluta che rappresenti l'eredità culturale e il design unico della Fiat 500. La missione è riunire appassionati di auto d'epoca e di criptovalute in una community globale.",
            "whitepaper_technology_title": "Tecnologia",
            "whitepaper_technology_text": "500 Crypto è un token SPL (Solana Program Library) creato sulla blockchain di Solana. Questa blockchain è stata scelta per la sua alta velocità di transazione, i bassi costi e la scalabilità.",
            "whitepaper_tokenomics_title": "Tokenomics",
            "whitepaper_tokenomics_1": "<strong>Nome del Token:</strong> 500 Crypto (500C)",
            "whitepaper_tokenomics_2": "<strong>Indirizzo Token:</strong> <a href=\"https://solscan.io/token/DdcrJRdNLB47bGdLZrcxVNfGAmvUbVXZKgY81Afcpump\" target=\"_blank\" rel=\"noopener noreferrer\">DdcrJRdNLB47bGdLZrcxVNfGAmvUbVXZKgY81Afcpump</a>",
            "whitepaper_tokenomics_3": "<strong>Supply Totale:</strong> 500.000.000 token",
            "whitepaper_tokenomics_4": "<strong>Autorità Mint:</strong> DdcrJRdNLB47bGdLZrcxVNfGAmvUbVXZKgY81Afcpump",
            "whitepaper_tokenomics_5": "<strong>Decimals:</strong> 6",
            "whitepaper_tokenomics_6": "<strong>Distribuzione:</strong> 50% vendita pubblica, 20% community, 15% sviluppo, 10% partnership, 5% team.",
            "whitepaper_utility_title": "Utility del Token",
            "whitepaper_utility_text": "Il token 500C offre accesso a eventi esclusivi, acquisto di NFT, governance della community e sconti presso partner selezionati. Inoltre, il token mira a diventare il metodo di pagamento preferito per beni e servizi nel settore delle auto d'epoca.",
            "whitepaper_roadmap_title": "Roadmap",
            "whitepaper_roadmap_1": "<strong>Fase 1:</strong> Lancio del token e creazione della community.",
            "whitepaper_roadmap_2": "<strong>Fase 2:</strong> Partnership con eventi di auto d'epoca.",
            "whitepaper_roadmap_3": "<strong>Fase 3:</strong> Lancio di un marketplace per NFT e memorabilia.",
            "whitepaper_conclusion_title": "Conclusione",
            "whitepaper_conclusion_text": "500 Crypto è un tributo alla Fiat 500, un'auto che ha segnato la storia dell'automobilismo. Unisciti a noi per celebrare questo mito e far parte di una community innovativa."
        },
        "en": {
            "title": "500 Crypto - The Vintage Fiat 500",
            "header_title": "500 Crypto",
            "header_subtitle": "The cryptocurrency celebrating the vintage Fiat 500",
            "about_title": "About Us",
            "about_text": "Welcome to the world of 500 Crypto, the cryptocurrency that celebrates the myth of the vintage Fiat 500. Join us to relive the magic of this iconic car.",
            "about_mission_label": "Mission:",
            "about_mission_text": "We are passionate about the iconic vintage Fiat 500 and believe that its history and unique design deserve a celebration in the world of cryptocurrencies. Our goal is to create a community of enthusiasts, combining the charm of the past with the innovations of the future.",
            "what_is_title": "What is 500 Crypto?",
            "what_is_text_1": "500 Crypto is a cryptocurrency based on the Solana blockchain. It was created to celebrate the vintage Fiat 500, one of the most iconic and beloved cars of all time. The token aims to create a community of vintage car and cryptocurrency enthusiasts.",
            "what_is_keypoints_label": "Key Points:",
            "what_is_keypoint_1": "<strong>Community:</strong> Unites vintage car and cryptocurrency enthusiasts.",
            "what_is_keypoint_2": "<strong>Decentralized:</strong> Operates on the Solana blockchain.",
            "what_is_keypoint_3": "<strong>Objective:</strong> Celebrates the vintage Fiat 500.",
            "roadmap_title": "Roadmap",
            "roadmap_phase_1_label": "Phase 1:",
            "roadmap_phase_1_text": "Launch of the token and creation of the community. (Complete)",
            "roadmap_phase_2_label": "Phase 2:",
            "roadmap_phase_2_text": "Development of partnerships with events dedicated to vintage cars. (In progress)",
            "roadmap_phase_3_label": "Phase 3:",
            "roadmap_phase_3_text": "Creation of a platform for the exchange of assets related to the Fiat 500 (coming soon)",
            "gallery_title": "Gallery",
            "chart_title": "Cryptocurrency Chart on Solana",
            "stats_title": "Cryptocurrency Statistics",
            "stats_text": "To view cryptocurrency statistics, visit the official page on ",
            "stats_link": "pump.fun",
            "contact_title": "Contact Us",
            "contact_name_label": "Name:",
            "contact_email_label": "Email:",
            "contact_message_label": "Message:",
            "contact_send_button": "Send",
            "footer_rights": "All rights reserved.",
            "whitepaper_title": "White Paper",
            "whitepaper_intro_title": "Introduction",
            "whitepaper_intro_text": "500 Crypto is a cryptocurrency based on the Solana blockchain, created to celebrate the iconic vintage Fiat 500. This token combines the charm of the past with the innovations of the future.",
            "whitepaper_vision_title": "Vision and Mission",
            "whitepaper_vision_text": "Our vision is to create a cryptocurrency that represents the cultural heritage and unique design of the Fiat 500. The mission is to bring together vintage car and cryptocurrency enthusiasts in a global community.",
            "whitepaper_technology_title": "Technology",
            "whitepaper_technology_text": "500 Crypto is an SPL (Solana Program Library) token created on the Solana blockchain. This blockchain was chosen for its high transaction speed, low costs, and scalability.",
            "whitepaper_tokenomics_title": "Tokenomics",
            "whitepaper_tokenomics_1": "<strong>Token Name:</strong> 500 Crypto (500C)",
            "whitepaper_tokenomics_2": "<strong>Token Address:</strong> <a href=\"https://solscan.io/token/DdcrJRdNLB47bGdLZrcxVNfGAmvUbVXZKgY81Afcpump\" target=\"_blank\" rel=\"noopener noreferrer\">DdcrJRdNLB47bGdLZrcxVNfGAmvUbVXZKgY81Afcpump</a>",
            "whitepaper_tokenomics_3": "<strong>Total Supply:</strong> 500,000,000 tokens",
            "whitepaper_tokenomics_4": "<strong>Mint Authority:</strong> DdcrJRdNLB47bGdLZrcxVNfGAmvUbVXZKgY81Afcpump",
            "whitepaper_tokenomics_5": "<strong>Decimals:</strong> 6",
            "whitepaper_tokenomics_6": "<strong>Distribution:</strong> 50% public sale, 20% community, 15% development, 10% partnerships, 5% team.",
            "whitepaper_utility_title": "Token Utility",
            "whitepaper_utility_text": "The 500C token offers access to exclusive events, purchase of NFTs, community governance, and discounts at selected partners. Additionally, the token aims to become the preferred payment method for goods and services in the vintage car sector.",
            "whitepaper_roadmap_title": "Roadmap",
            "whitepaper_roadmap_1": "<strong>Phase 1:</strong> Token launch and community creation.",
            "whitepaper_roadmap_2": "<strong>Phase 2:</strong> Partnerships with vintage car events.",
            "whitepaper_roadmap_3": "<strong>Phase 3:</strong> Launch of a marketplace for NFTs and memorabilia.",
            "whitepaper_conclusion_title": "Conclusion",
            "whitepaper_conclusion_text": "500 Crypto is a tribute to the Fiat 500, a car that has marked the history of motoring. Join us to celebrate this icon and be part of an innovative community."
        },
        // Additional translations for Chinese and French can be added in similar fashion.
    };

    // Define the current language. For now, it's Italian.
    let currentLang = "it"; // Can be changed to "en", "fr", or "cn"

    function updatePageLanguage() {
        const elements = document.querySelectorAll("[data-translate]");
        elements.forEach(function(element) {
            const translationKey = element.getAttribute("data-translate");
            if (translations[currentLang] && translations[currentLang][translationKey]) {
                element.innerHTML = translations[currentLang][translationKey];
            }
        });
    }

    // Initialize the page in the selected language.
    updatePageLanguage();
});
