document.addEventListener('DOMContentLoaded', function() {
    const translations = {
       "it": {
            "title": "500 Crypto - La Fiat 500 d'epoca",
            "header_title": "500 Crypto",
            "header_subtitle": "La criptovaluta che celebra il mito della Fiat 500 d'epoca",
            "about_title": "Chi Siamo",
            "about_text": "Benvenuti nel mondo di 500 Crypto, la criptovaluta che celebra il mito della Fiat 500 d'epoca. Unisciti a noi per rivivere la magia di questa iconica automobile.",
            "about_mission_label": "Missione:",
            "about_mission_text": "Siamo appassionati dell'iconica Fiat 500 d'epoca e crediamo che la sua storia e il suo design unico meritino una celebrazione nel mondo delle criptovalute. Il nostro obiettivo è creare una community di appassionati, unendo il fascino del passato con le innovazioni del futuro.",
            "what_is_title": "Cos'è 500 Crypto?",
            "what_is_text_1": "500 Crypto è una criptovaluta basata sulla blockchain di Solana. È stata creata per celebrare la Fiat 500 d'epoca, una delle auto più iconiche e amate di tutti i tempi. Il token mira a creare una community di appassionati di auto d'epoca e di criptovalute.",
            "what_is_keypoints_label": "Punti Chiave:",
            "what_is_keypoint_1": "<strong>Community:</strong> Unisce appassionati di auto d'epoca e criptovalute.",
            "what_is_keypoint_2": "<strong>Decentralizzata:</strong> Opera sulla blockchain di Solana.",
            "what_is_keypoint_3": "<strong>Obiettivo:</strong> Celebra la Fiat 500 d'epoca.",
            "roadmap_title": "Roadmap",
            "roadmap_phase_1_label": "Fase 1:",
            "roadmap_phase_1_text": "Lancio del token e creazione della community. (Completa)",
            "roadmap_phase_2_label": "Fase 2:",
            "roadmap_phase_2_text": "Sviluppo di partnership con eventi dedicati ad auto d'epoca. (In corso)",
            "roadmap_phase_3_label": "Fase 3:",
            "roadmap_phase_3_text": "Creazione di una piattaforma per lo scambio di asset legati alla Fiat 500 (prossimamente)",
            "gallery_title": "Galleria",
            "chart_title": "Grafico della Criptovaluta su Solana",
            "stats_title": "Statistiche della Criptovaluta",
            "stats_text": "Per visualizzare le statistiche della criptovaluta, visita la pagina ufficiale su ",
            "stats_link": "pump.fun",
            "contact_title": "Contattaci",
            "contact_name_label": "Nome:",
            "contact_email_label": "Email:",
            "contact_message_label": "Messaggio:",
            "contact_send_button": "Invia",
            "footer_rights": "Tutti i diritti riservati."
        },
        "en": {
           "title": "500 Crypto - The Vintage Fiat 500",
            "header_title": "500 Crypto",
            "header_subtitle": "The cryptocurrency celebrating the vintage Fiat 500",
            "about_title": "About Us",
            "about_text": "Welcome to the world of 500 Crypto, the cryptocurrency that celebrates the myth of the vintage Fiat 500. Join us to relive the magic of this iconic car.",
            "about_mission_label": "Mission:",
            "about_mission_text": "We are passionate about the iconic vintage Fiat 500 and believe that its history and unique design deserve a celebration in the world of cryptocurrencies. Our goal is to create a community of enthusiasts, combining the charm of the past with the innovations of the future.",
           "what_is_title": "What is 500 Crypto?",
            "what_is_text_1": "500 Crypto is a cryptocurrency based on the Solana blockchain. It was created to celebrate the vintage Fiat 500, one of the most iconic and beloved cars of all time. The token aims to create a community of vintage car and cryptocurrency enthusiasts.",
            "what_is_keypoints_label": "Key Points:",
            "what_is_keypoint_1": "<strong>Community:</strong> Unites vintage car and cryptocurrency enthusiasts.",
            "what_is_keypoint_2": "<strong>Decentralized:</strong> Operates on the Solana blockchain.",
            "what_is_keypoint_3": "<strong>Objective:</strong> Celebrates the vintage Fiat 500.",
            "roadmap_title": "Roadmap",
            "roadmap_phase_1_label": "Phase 1:",
            "roadmap_phase_1_text": "Launch of the token and creation of the community. (Complete)",
            "roadmap_phase_2_label": "Phase 2:",
            "roadmap_phase_2_text": "Development of partnerships with events dedicated to vintage cars. (In progress)",
            "roadmap_phase_3_label": "Phase 3:",
            "roadmap_phase_3_text": "Creation of a platform for the exchange of assets related to the Fiat 500 (coming soon)",
            "gallery_title": "Gallery",
            "chart_title": "Cryptocurrency Chart on Solana",
            "stats_title": "Cryptocurrency Statistics",
            "stats_text": "To view cryptocurrency statistics, visit the official page on ",
            "stats_link": "pump.fun",
            "contact_title": "Contact Us",
            "contact_name_label": "Name:",
            "contact_email_label": "Email:",
            "contact_message_label": "Message:",
            "contact_send_button": "Send",
            "footer_rights": "All rights reserved."
          },
        "zh": {
            "title": "500 加密貨幣 - 經典菲亞特500",
            "header_title": "500 加密貨幣",
            "header_subtitle": "慶祝經典菲亞特500的加密貨幣",
            "about_title": "關於我們",
            "about_text": "歡迎來到500 加密貨幣的世界，這是一種慶祝經典菲亞特500神話的加密貨幣。加入我們，重溫這款標誌性汽車的魔力。",
            "about_mission_label": "使命:",
            "about_mission_text": "我們對標誌性的經典菲亞特500充滿熱情，並認為其歷史和獨特設計值得在加密貨幣世界中慶祝。我們的目標是創建一個愛好者社區，將過去的魅力與未來的創新結合起來。",
            "what_is_title": "什麼是 500 加密貨幣?",
            "what_is_text_1": "500 加密貨幣是一種基於 Solana 區塊鏈的加密貨幣。它的創建是為了慶祝經典菲亞特500，這是有史以來最具標誌性和最受喜愛的汽車之一。該代幣旨在創建一個經典汽車和加密貨幣愛好者的社區。",
            "what_is_keypoints_label": "關鍵要點:",
            "what_is_key
